name: Lint Docs

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  rubocop:
    name: "rubocop:md"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3
    - name: Lint docs with RuboCop
      run: |
        bundle install --jobs 4 --retry 3
        bundle exec rake rubocop:md
