name: Lint

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2
    - name: Lint Ruby code with RuboCop
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rubocop
